language: python
python:
    - "2.7"
    # - "3.3"

env:
    global:
        - PACKAGE="remote-sublime"
    matrix:
        #- SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

install:
    - sh -e travis.sh $SUBLIME_TEXT_VERSION $PACKAGE

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - python $HOME/.config/sublime-text-$SUBLIME_TEXT_VERSION/Packages/UnitTesting/sbin/run.py $PACKAGE

notifications:
    email: true
